export const GOKU_SAMPLE = {
    personalDetailsForm: {
      name: 'Ayush Thakur',
      phone: '9650218723',
      email: 'ayushthakur2009@gmail.com',
      state: 'Karnataka',
      city: 'Bengaluru',
      pincode: '560037',
      linkedIn: 'https://www.linkedin.com/in/ayush-thakur/'
    },
    professionalDetailsForm: {
      objective: 'Working in the IT industry, I have got the opportunity to work on varied technologies throughout my career. At this moment looking to further apply my expertise in JS frameworks like Angular & React, along with my experience in multiple technologies & domains to help an organization reach its delivery goals, with best quality code and in minimal time frames',
      skills: [
        'Angular',
        'React',
        'javascript',
        'bootstrap',
        'node.js',
        'webpack',
        'HTML',
        'CSS',
        'GIT',
        'mongoDB',
        'java',
        'jersey'
      ],
      experience: [
        {
          companyName: 'FIS',
          companyCity: 'Bengaluru',
          designation: 'Software Engineer II',
          startDate: '2019-12-15T18:30:00.000Z',
          endDate: '2020-09-22T09:47:19.667Z',
          workDesc: 'Working on upgrading legacy banking application suite to modern tech stack with angular being used on ui along with angular material. Work involves delivering features and bug fixes for different modules and finding innovative & optimal solution to complex problems. Also, guiding colleagues new to angular',
          isPresent: true
        },
        {
          companyName: 'Zycus Infotech Pvt. Ltd.',
          companyCity: 'Bengaluru',
          designation: 'Associate Tech Lead',
          startDate: '2018-07-24T18:30:00.000Z',
          endDate: '2019-12-12T18:30:00.000Z',
          workDesc: 'Worked on creating P2P products from scratch using angular technology, delivering optimized code with recommended best practices from angular community which enabled us to create a smooth user experience. \nTook lead on creating common components sub module which is used by all products to provide the same experience to end users who use multiple products from the suite provided by the organization. The common components are easy to use and integrate and saved lot of development time. \nProven experience in training and managing colleagues as well as taking complete ownership of not only my product but the complete product suite by unblocking all technical issues related to front end and also by providing innovative solutions. Coming up with new benchmarks and quality improvement techniques to improve the standard of coding done.',
          isPresent: false
        },
        {
          companyName: 'Infosys Ltd.',
          companyCity: 'Bengaluru',
          designation: 'System Engineer',
          startDate: '2016-01-24T18:30:00.000Z',
          endDate: '2018-07-23T18:30:00.000Z',
          workDesc: 'System Engineer - Working on web development for client that will enable them to analyze data generated by the hardware telecommunication devices through use of sensors. Working on the front-end part (angular 2) and the middle layer (java) Also, scripting in shell and python as per requirement. Working with docker and kubernetes as well.\nSystem Engineer - Replaced the hardware security card used by the device of the telecommunications client with an open source FreeBSD license-based library (LibSRTP) so that the cost of external physical cards for encrypting RTP calls would come down hence reducing the build cost while leveraging the benefits of open source software.\nSystem Trainee Engineer - Created a website that could be accessed through mobile phones as well as computer (front end created to dynamically adjust to screen size) which would enable the administrator or manager to monitor the processes running on other systems in the network. Also, the person logged in to the web site would have the power to start new processes or end running processes in the systems connected to the network.\nSystem Trainee Engineer - On completing standard training with core stream as java and basic training in python I was given extra training in C/C++ in the networking domain. In Linux based environment using putty we created a transaction manager that utilized the concept of threads to use a single resource to transport messages between clients and server. Proper logging mechanisms were also created to handle unexpected errors.',
          isPresent: false
        }
      ]
    },
    educationDetailsForm: {
      education: [
        {
          instituteName: 'Galgotias University',
          instituteCity: 'Greater Noida',
          qualification: 'BACHELOR OF TECHNOLOGY (CSE)',
          marksObtained: 92.9,
          totalMarks: 100,
          passDate: '2016-06-30T18:30:00.000Z'
        },
        {
          instituteName: 'Little Flower School',
          instituteCity: 'Jamshedpur',
          qualification: 'ISC (12TH BOARD EXAM)',
          marksObtained: 91,
          totalMarks: 100,
          passDate: '2012-06-30T18:30:00.000Z'
        },
        {
          instituteName: 'Little Flower School',
          instituteCity: 'Jamshedpur',
          qualification: 'ICSE (10TH BOARD EXAM)',
          marksObtained: 92.57,
          totalMarks: 100,
          passDate: '2010-06-30T18:30:00.000Z'
        }
      ]
    },
    additionalDetailsForm: {
      additionalInfo: 'My Portfolio - https://ayush-portfolio-app.herokuapp.com/ \nLive personal project on MEAN stack deployed as docker image - https://blitz-builder.herokuapp.com/\nYoutube Channel (Angular tutorials) - https://www.youtube.com/playlist?list=PLZdPgkRI3ruiOnkAoA7UGi_ueg4PuB8qB\nReceived monthly appreciation in all project & companies I have worked in.\nConsistent academic performer scoring above 90% throughout\nIn extra-curricular actively involved in the field of music and sports'
    }
  };
